### ISSUE TITLE
[Packaging | `jsonschema` compatibility ] - test and follow up Reana's proposed solution

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/reana-jupyterlab-extension#11]
After Marco's comment on Mattermost (see below), test and follow up with REANA team the proposed solution
https://github.com/mdonadoni/reana-client/tree/vre-summer-24

"""
I am hosting the custom version of reana-client here: https://github.com/mdonadoni/reana-client/tree/vre-summer-24
which install a version of commons that does not require any particular version of jsonschema: https://github.com/mdonadoni/reana-commons/tree/vre-summer-24

You should be able to install it with pip install git+https://github.com/mdonadoni/reana-client.git@vre-summer-24.

Let me know if this is a feasible workaround for you. (of course yadage still does not work)
"""

**Comment by rubenperezm** [comment]
I have been testing the custom version of `reana-client` and it seems to work.

However, the module  (the main version and the custom one) seems to be read/loaded after the first request (and not before), which means that the first request uses the default URL, and from the second request onwards the custom env variable is used.

In order to solve that, we had 3 possibilities:

1. Set the environment variable before calling the script (as we let the user change the server URL and the code to connect to REANA is executed when JupyterLAb is launched, this would not be possible).
2. Import `reana_client.api.client` after setting the variables (works fine in scripts but does not seem to work in JupyterLab Server).
3. Creating a client after setting the variables, which forces to reload the URL (works fine, but might break if they change that part of the codebase).

In my opinion, we should use the last option. The first one is impossible to implement in this project, and even if the second option was not impossible, it would take more time to make it work in JupyterLab Server. If in the future we plan to update `reana_client` or `reana_commons`, it may be necessary to refactor the `POST` method in `EnvVariablesHandler` (`jupyterlab_reana/handlers/connection.py`).

**Comment by rubenperezm** [comment]
This is the line that solved our problem:
https://github.com/vre-hub/reana-jupyterlab-extension/blob/a34082dd13969119a8bda17642ba3d8b902b1e49/jupyterlab_reana/handlers/connection.py#L11
